In [4]:
import tensorflow as tf

In [7]:
print(tf.__version__)

2.4.1


In [2]:
###tensores

In [10]:
cadena= tf.Variable("esto es una cadena", tf.string)
numero= tf.Variable(324, tf.int16)
flotante= tf.Variable(3.2527, tf.float64)
print(flotante)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.2527>


In [12]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [17]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
print(tensor1)                                        # this will reshape the tensor to [3,3]
                                                                             


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [18]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
